# Generated by Django 5.0.6 on 2024-06-01 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastr_num', models.CharField(max_length=255)),
                ('other_school_lang', models.CharField(blank=True, max_length=255)),
                ('erp_mahalla_id', models.IntegerField(blank=True, null=True)),
                ('erp_mahalla', models.CharField(blank=True, max_length=255)),
                ('address_uid', models.CharField(blank=True, max_length=255)),
                ('house_type', models.CharField(blank=True, max_length=255)),
                ('district_uid', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('district_soato', models.CharField(blank=True, max_length=255)),
                ('street_uid', models.CharField(blank=True, max_length=255)),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=255)),
                ('object_type', models.CharField(blank=True, max_length=255)),
                ('coords', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymaktab.coord')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('school_num', models.CharField(max_length=255)),
                ('study_lang', models.IntegerField()),
                ('houses', models.ManyToManyField(blank=True, to='mymaktab.houses')),
                ('locations', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymaktab.coord')),
            ],
        ),
    ]
