# Generated by Django 5.0.6 on 2024-06-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymaktab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='street',
        ),
        migrations.DeleteModel(
            name='LanguageEducation',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='region',
        ),
        migrations.RemoveField(
            model_name='street',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='region',
            name='oblast',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.DeleteModel(
            name='Oblast',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
